version: '3'

# Define variables
vars:
  MAIN_IMAGE_NAME: {{cookiecutter.project_slug}}
  DEV_IMAGE_NAME: {{cookiecutter.project_slug}}_dev
  IMAGE_VERSION: 0.1.0

tasks:
  # Default task that runs when no task is specified
  default:
    desc: "Welcome to {{cookiecutter.project_name}}."
    cmds:
      - echo "Welcome to {{cookiecutter.project_name}}."

